const fs = require('fs');
const path = require('path');
const postcss = require('postcss');
const tailwindcss = require('@tailwindcss/postcss');

async function build() {
  const inputCssPath = path.join(__dirname, '../src/index.css');
  const outputTsPath = path.join(__dirname, '../src/generated-styles.ts');
  const css = fs.readFileSync(inputCssPath, 'utf8');

  const result = await postcss([
    tailwindcss()
  ]).process(css, { from: inputCssPath, to: outputTsPath });

  let cleanedCss = result.css;

  // 1. Remove global layer order re-declarations
  cleanedCss = cleanedCss.replace(/@layer\s+theme,\s*base,\s*components,\s*utilities;/g, '');
  cleanedCss = cleanedCss.replace(/@layer\s+properties;/g, '');

  // 2. Replace global :root, :host and html with .hellokit-editor-scope
  cleanedCss = cleanedCss.replace(/:root,\s*:host/g, '.hellokit-editor-scope');
  cleanedCss = cleanedCss.replace(/html,\s*:host/g, '.hellokit-editor-scope');

  // 3. Prefix EVERY single rule selector in base, utilities, and components with .hellokit-editor-scope
  cleanedCss = cleanedCss.replace(
    /([^{}]+)\{([^{}]+)\}/g,
    (ruleMatch, selectors, body) => {
      if (
        selectors.includes('@') ||
        selectors.includes('keyframes')
      ) {
        return ruleMatch;
      }
      const scopedSelectors = selectors
        .split(',')
        .map((s) => {
          const trimmed = s.trim();
          if (!trimmed) return trimmed;
          if (trimmed.startsWith('.hellokit-editor-scope')) return trimmed;
          if (trimmed.startsWith('.dark') || trimmed.includes('.dark')) {
            if (trimmed.includes('.hellokit-editor-scope')) return trimmed;
            return `.dark .hellokit-editor-scope ${trimmed.replace('.dark', '').trim()}`;
          }
          return `.hellokit-editor-scope ${trimmed}`;
        })
        .join(', ');
      return `${scopedSelectors} {${body}}`;
    }
  );

  // 4. Wrap entire package CSS in an isolated cascade layer
  cleanedCss = `@layer hellokit-editor-layer {\n${cleanedCss}\n}`;

  const content = `// Auto-generated by scripts/build-css.js - DO NOT EDIT MANUALLY\nexport const PACKAGE_STYLES = ${JSON.stringify(cleanedCss)};\n`;

  fs.writeFileSync(outputTsPath, content, 'utf8');
  console.log('Successfully generated src/generated-styles.ts with dark mode & scope support');
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
