const fs = require('fs');
const path = require('path');
const postcss = require('postcss');

async function build() {
  const inputCssPath = path.join(__dirname, '../dist/temp.css');
  const outputTsPath = path.join(__dirname, '../src/generated-styles.ts');
  
  if (!fs.existsSync(inputCssPath)) {
    console.error("temp.css not found! Make sure to run tailwindcss CLI first.");
    process.exit(1);
  }
  
  try {
    let css = fs.readFileSync(inputCssPath, 'utf8');

    // 1. Remove layer directives (Tailwind v4 adds these)
    css = css.replace(/@layer\s+theme,\s*base,\s*components,\s*utilities;/g, '');
    css = css.replace(/@layer\s+properties;/g, '');
    css = css.replace(/@layer\s+theme;/g, '');
    
    // 2. We don't want to scope :root and variables because they need to be available
    const prefixPlugin = () => {
      return {
        postcssPlugin: 'scope-plugin',
        Rule(rule) {
          // Skip if inside @layer properties or @property
          if (rule.parent && rule.parent.name === 'property') return;
          // Skip if inside @keyframes
          if (rule.parent && rule.parent.type === 'atrule' && rule.parent.name === 'keyframes') return;
          // Skip variables or root
          if (rule.selector.includes(':root') || rule.selector.includes(':host')) return;
          if (rule.selector.includes('.hellokit-editor-scope')) return;

          rule.selectors = rule.selectors.map(selector => {
            // Clean up empty lines or weird spaces
            const cleanSelector = selector.trim();
            if (!cleanSelector) return cleanSelector;
            
            // If the selector contains .dark, the .dark class must be outside the scope
            // For example: .dark .bg-white -> .dark .hellokit-editor-scope .bg-white
            if (cleanSelector.startsWith('.dark ') || cleanSelector.includes('.dark ')) {
              return cleanSelector.replace('.dark ', '.dark .hellokit-editor-scope ');
            }
            if (cleanSelector === '.dark' || cleanSelector === ':where(.dark)') return cleanSelector;

            return `.hellokit-editor-scope ${cleanSelector}`;
          });
        }
      };
    };
    prefixPlugin.postcss = true;

    const result = await postcss([prefixPlugin()]).process(css, { from: inputCssPath });
    let cleanedCss = result.css;

    // Wrap in a custom layer to avoid specificity issues (optional, but good practice)
    const finalCss = `@layer hellokit-editor-layer {\n${cleanedCss}\n}`;

    const tsContent = `// Auto-generated by scripts/build-css.js - DO NOT EDIT MANUALLY\nexport const PACKAGE_STYLES = ${JSON.stringify(finalCss)};\n`;

    fs.writeFileSync(outputTsPath, tsContent);
    console.log('Successfully generated src/generated-styles.ts with dark mode & scope support');

    // Keep src/tailwind.css in sync too. It's imported directly by
    // src/index.ts (used when a bundler resolves this package's
    // "development" export condition, e.g. running the example app straight
    // against source instead of dist/). It used to be a hand-maintained copy
    // of editor-styles.css with no automated regeneration step at all, so it
    // silently drifted out of sync whenever editor-styles.css changed.
    // editor-styles.css is the actual source of truth, so just mirror it.
    const editorStylesPath = path.join(__dirname, '../src/editor-styles.css');
    const tailwindCssPath = path.join(__dirname, '../src/tailwind.css');
    const editorStylesSource = fs.readFileSync(editorStylesPath, 'utf8');
    const tailwindCssContent =
      '/*! Auto-synced from src/editor-styles.css by scripts/build-css.js - DO NOT EDIT MANUALLY */\n' +
      editorStylesSource;
    fs.writeFileSync(tailwindCssPath, tailwindCssContent);
    console.log('Synced src/tailwind.css from src/editor-styles.css');

  } catch (err) {
    console.error('Error generating styles:', err);
    process.exit(1);
  }
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
